//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_N6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> InsertDateUsuario { get; set; }
        public Nullable<System.DateTime> UpdateUsuario { get; set; }
        public string Ip { get; set; }
        public string Usuario1 { get; set; }
    }
}
